
services:
  swagger-combine-ui:
    build:
      context: ./
      args:
        NODE_ENV: development
        USER: root
    environment:
      EXTERNAL_HTTP_PORT: 4000
      SWAGGER_CONFIG_PATH: /app/config/swagger.yaml
    command:
      - npm
      - run
      - dev
    ports:
      - "4000:3000"
    volumes:
      - "./package.json:/app/package.json"
      - "./lib:/app/lib"
      - "./index.js:/app/index.js"
      - "./index.html:/app/index.html"
      - "./swagger.yaml:/app/config/swagger.yaml"